"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PageContainer } from "@/components/ui/container";
import { calculateCohortMetrics } from "@/lib/program/cohorts";
import { validateCohort, validateRosterMember } from "@/lib/program/admin";
import type { ApprovedMember, AppRole, CohortEnrollment, ProgramQuarter } from "@/lib/program/types";
import { formatCohortLabel } from "@/lib/program/state";
import { useAdminWorkspace } from "./admin-workspace";

const control = "min-h-11 rounded-lg border border-border-strong bg-surface px-3 text-sm text-ink";

function ParticipantRow({ enrollment, name, email, announce }: { enrollment: CohortEnrollment; name?: string; email?: string; announce: (value: string) => void }) {
  const workspace = useAdminWorkspace();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(enrollment);
  const dirty = JSON.stringify(draft) !== JSON.stringify(enrollment);
  function setAdvancement(value: CohortEnrollment["advancementStatus"]) {
    setDraft(value === "promoted" ? { ...draft, advancementStatus: "promoted", promotionResponse: "pending" } : { id: draft.id, cohortId: draft.cohortId, personId: draft.personId, participationStatus: draft.participationStatus, advancementStatus: value });
  }
  return <Card className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-bold">{name}</p><p className="mt-1 text-sm text-ink-soft">{email}</p>{!editing ? <p className="mt-2 text-sm capitalize text-ink-soft">{enrollment.participationStatus} · {enrollment.advancementStatus.replace("_", " ")}{enrollment.advancementStatus === "promoted" ? ` · ${enrollment.promotionResponse}` : ""}</p> : null}</div><Button size="compact" variant="secondary" onClick={() => { setDraft(enrollment); setEditing((value) => !value); }}>{editing ? "Cancel" : "Edit outcomes"}</Button></div>
    {editing ? <div className="mt-5 grid gap-4 border-t border-border pt-5 md:grid-cols-3"><label className="text-xs font-bold uppercase tracking-[0.1em] text-ink-faint">Participation<select className={`mt-2 w-full ${control}`} value={draft.participationStatus} onChange={(event) => setDraft({ ...draft, participationStatus: event.target.value as CohortEnrollment["participationStatus"] })}>{["enrolled", "completed", "withdrew"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-bold uppercase tracking-[0.1em] text-ink-faint">Advancement<select className={`mt-2 w-full ${control}`} value={draft.advancementStatus} onChange={(event) => setAdvancement(event.target.value as CohortEnrollment["advancementStatus"])}>{["pending", "promoted", "not_promoted"].map((value) => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select></label>{draft.advancementStatus === "promoted" ? <label className="text-xs font-bold uppercase tracking-[0.1em] text-ink-faint">Response<select className={`mt-2 w-full ${control}`} value={draft.promotionResponse} onChange={(event) => setDraft({ ...draft, promotionResponse: event.target.value as "pending" | "joined" | "declined" })}>{["pending", "joined", "declined"].map((value) => <option key={value}>{value}</option>)}</select></label> : null}<div className="md:col-span-3"><Button size="compact" disabled={!dirty} onClick={() => { workspace.updateEnrollment(draft); setEditing(false); announce("Participant outcomes saved."); }}>Save outcomes</Button></div></div> : null}
  </Card>;
}

function RosterRow({ member, announce }: { member: ApprovedMember; announce: (value: string) => void }) {
  const workspace = useAdminWorkspace(); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(member);
  function save() { const error = validateRosterMember(draft, workspace.approvedMembers, member.id); if (error) return announce(error); workspace.updateApprovedMember({ ...draft, email: draft.email.trim().toLowerCase(), fullName: draft.fullName.trim() }); setEditing(false); announce("Portal access saved."); }
  return <Card className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-bold">{member.fullName}</p><p className="mt-1 text-sm text-ink-soft">{member.email} · {member.role} · {member.active ? "active" : "inactive"}</p></div><Button size="compact" variant="secondary" onClick={() => { setDraft(member); setEditing((value) => !value); }}>{editing ? "Cancel" : "Edit access"}</Button></div>{editing ? <div className="mt-5 grid gap-4 border-t border-border pt-5 md:grid-cols-3"><label className="text-sm font-bold">Full name<input className={`mt-2 w-full ${control}`} value={draft.fullName} onChange={(event) => setDraft({ ...draft, fullName: event.target.value })} /></label><label className="text-sm font-bold">UC Davis email<input className={`mt-2 w-full ${control}`} value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })} /></label><label className="text-sm font-bold">Role<select className={`mt-2 w-full ${control}`} value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value as AppRole })}><option value="member">Member</option><option value="admin">Admin</option></select></label><div className="flex flex-wrap gap-2 md:col-span-3"><Button size="compact" onClick={save}>Save access</Button><Button size="compact" variant={draft.active ? "danger" : "secondary"} onClick={() => setDraft({ ...draft, active: !draft.active })}>{draft.active ? "Deactivate" : "Reactivate"}</Button></div></div> : null}</Card>;
}

export function AdminMembers() {
  const workspace = useAdminWorkspace();
  const [view, setView] = useState<"participants" | "access">("participants"); const [message, setMessage] = useState(""); const [search, setSearch] = useState(""); const [showAdd, setShowAdd] = useState(false); const [showCohorts, setShowCohorts] = useState(false); const [newPersonId, setNewPersonId] = useState("");
  const [rosterForm, setRosterForm] = useState({ fullName: "", email: "", role: "member" as AppRole }); const [cohortForm, setCohortForm] = useState({ quarter: "winter" as ProgramQuarter, year: 2027, startsOn: "2027-01-04", endsOn: "2027-03-19" });
  const cohort = workspace.cohorts.find((item) => item.id === workspace.selectedCohortId); const enrollments = workspace.enrollments.filter((item) => item.cohortId === workspace.selectedCohortId); const enrolledIds = new Set(enrollments.map((item) => item.personId)); const eligible = workspace.people.filter((person) => !enrolledIds.has(person.id)); const metrics = calculateCohortMetrics(enrollments); const query = search.trim().toLowerCase();
  const filteredEnrollments = enrollments.filter((item) => { const person = workspace.people.find((candidate) => candidate.id === item.personId); return !query || `${person?.fullName} ${person?.email}`.toLowerCase().includes(query); }); const filteredRoster = workspace.approvedMembers.filter((member) => !query || `${member.fullName} ${member.email}`.toLowerCase().includes(query));
  function createCohort() { const error = validateCohort(cohortForm, workspace.cohorts); if (error) return setMessage(error); workspace.createCohort({ id: `cohort-${crypto.randomUUID()}`, ...cohortForm, state: "draft" }); setMessage(`${formatCohortLabel(cohortForm)} created with six draft weeks.`); }
  function addRoster() { const error = validateRosterMember(rosterForm, workspace.approvedMembers); if (error) return setMessage(error); workspace.addApprovedMember(rosterForm); setRosterForm({ fullName: "", email: "", role: "member" }); setShowAdd(false); setMessage("Roster member added."); }
  const success = /saved|added|created|updated/.test(message.toLowerCase());
  return <main className="pb-20 sm:pb-24"><PageContainer className="py-9 sm:py-11"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-brand-deep">People and access</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.035em] sm:text-4xl">Members</h1><p className="mt-3 max-w-3xl text-base leading-7 text-ink-soft">Manage cohort participation separately from permission to enter the portal.</p></div><Button variant="secondary" onClick={() => setShowCohorts((value) => !value)}>Manage cohort</Button></div>
    {showCohorts ? <Card className="mt-6 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-bold">{cohort ? formatCohortLabel(cohort) : "Selected cohort"}</p><p className="mt-1 text-sm capitalize text-ink-soft">{cohort?.state}</p></div><div className="flex flex-wrap gap-2">{cohort?.state === "draft" ? <Button size="compact" onClick={() => { workspace.setSelectedCohortState("active"); setMessage("Cohort activated."); }}>Activate</Button> : null}{cohort?.state === "active" ? <Button size="compact" variant="danger" onClick={() => workspace.setSelectedCohortState("archived")}>Archive</Button> : null}</div></div><details className="mt-5 border-t border-border pt-5"><summary className="cursor-pointer font-bold">Create another cohort</summary><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold">Quarter<select className={`mt-2 w-full ${control}`} value={cohortForm.quarter} onChange={(event) => setCohortForm({ ...cohortForm, quarter: event.target.value as ProgramQuarter })}>{["winter", "spring", "fall"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-bold">Year<input className={`mt-2 w-full ${control}`} type="number" value={cohortForm.year} onChange={(event) => setCohortForm({ ...cohortForm, year: Number(event.target.value) })} /></label><label className="text-sm font-bold">Starts<input className={`mt-2 w-full ${control}`} type="date" value={cohortForm.startsOn} onChange={(event) => setCohortForm({ ...cohortForm, startsOn: event.target.value })} /></label><label className="text-sm font-bold">Ends<input className={`mt-2 w-full ${control}`} type="date" value={cohortForm.endsOn} onChange={(event) => setCohortForm({ ...cohortForm, endsOn: event.target.value })} /></label></div><Button className="mt-5" onClick={createCohort}>Create cohort</Button></details></Card> : null}
    <div className="mt-8 flex gap-2 border-b border-border">{(["participants", "access"] as const).map((item) => <button key={item} onClick={() => { setView(item); setMessage(""); setShowAdd(false); }} className={`min-h-11 border-b-2 px-4 text-sm font-bold ${view === item ? "border-action text-action" : "border-transparent text-ink-soft"}`}>{item === "participants" ? "Cohort participants" : "Portal access"}</button>)}</div>{message ? <p className={`mt-5 text-sm font-bold ${success ? "text-success-text" : "text-danger-text"}`} role="status">{message}</p> : null}
    <section className="mt-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold">{view === "participants" ? "Cohort participants" : "Portal access"}</h2><p className="mt-2 text-sm text-ink-soft">{view === "participants" ? "Permanent participation and advancement outcomes." : "Approved identities, roles, and portal availability."}</p></div><Button onClick={() => setShowAdd((value) => !value)}>{showAdd ? "Close" : view === "participants" ? "Add participant" : "Add roster member"}</Button></div>
      {showAdd ? <Card className="mt-5 p-6">{view === "participants" ? <div className="flex flex-wrap gap-3"><select className={control} value={newPersonId} onChange={(event) => setNewPersonId(event.target.value)}><option value="">Choose roster member</option>{eligible.map((person) => <option key={person.id} value={person.id}>{person.fullName}</option>)}</select><Button disabled={!newPersonId} onClick={() => { workspace.addEnrollment(newPersonId); setNewPersonId(""); setShowAdd(false); setMessage("Participant added."); }}>Add to cohort</Button></div> : <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Full name<input className={`mt-2 w-full ${control}`} value={rosterForm.fullName} onChange={(event) => setRosterForm({ ...rosterForm, fullName: event.target.value })} /></label><label className="text-sm font-bold">UC Davis email<input className={`mt-2 w-full ${control}`} value={rosterForm.email} onChange={(event) => setRosterForm({ ...rosterForm, email: event.target.value })} /></label><label className="text-sm font-bold">Role<select className={`mt-2 w-full ${control}`} value={rosterForm.role} onChange={(event) => setRosterForm({ ...rosterForm, role: event.target.value as AppRole })}><option value="member">Member</option><option value="admin">Admin</option></select></label><div className="md:col-span-3"><Button onClick={addRoster}>Add to roster</Button></div></div>}</Card> : null}
      <input className={`mt-5 w-full sm:max-w-sm ${control}`} type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or email" aria-label="Search members" /><div className="mt-5 space-y-3">{view === "participants" ? filteredEnrollments.map((enrollment) => { const person = workspace.people.find((item) => item.id === enrollment.personId); return <ParticipantRow key={enrollment.id} enrollment={enrollment} name={person?.fullName} email={person?.email} announce={setMessage} />; }) : filteredRoster.map((member) => <RosterRow key={member.id} member={member} announce={setMessage} />)}</div>
    </section>
    {view === "participants" ? <section className="mt-14 border-t border-border pt-10" aria-label="Cohort outcomes"><h2 className="text-2xl font-bold">Cohort outcomes</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Starters", metrics.starters, `${metrics.withdrew} withdrawn`], ["Advancement", metrics.advancementRate === undefined ? "—" : `${Math.round(metrics.advancementRate * 100)}%`, `${metrics.promoted}/${metrics.promoted + metrics.notPromoted} finalized`], ["Offer yield", metrics.offerYield === undefined ? "—" : `${Math.round(metrics.offerYield * 100)}%`, `${metrics.joined}/${metrics.joined + metrics.declined} finalized`], ["End-to-end", metrics.endToEndConversion === undefined ? "—" : `${Math.round(metrics.endToEndConversion * 100)}%`, `${metrics.joined}/${metrics.starters} starters`]].map(([label, value, detail]) => <Card className="p-5" key={label}><p className="text-sm text-ink-soft">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-ink-soft">{detail}</p></Card>)}</div></section> : null}
  </PageContainer></main>;
}
